name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change to 'master' if that's your main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Change to 'master' if that's your main branch

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # === FRAMEWORK-SPECIFIC BUILD STEPS ===
      # Uncomment the appropriate section for your framework
      
      # === REACT/NEXT.JS BUILD ===
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        env:
          CI: false  # Prevents treating warnings as errors in React
      
      # === END FRAMEWORK-SPECIFIC BUILD STEPS ===

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/"              # Location of your app's source code
          api_location: "api"            # Location of Azure Functions code (if any, otherwise "")
          output_location: "build"       # Location of built files (e.g., "build" for React, "dist" for Vue)
          ###### End of Repository/Build Configurations ######
          skip_app_build: true           # Skip build step as we've already built the app

      # Optional: Copy routes.json to the output directory if needed
      - name: Copy routes.json for SPA routing
        if: success()
        run: |
          if [ -f "routes.json" ] && [ -d "build" ]; then
            cp routes.json build/
          fi

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"